### ISSUE TITLE
portaudio-go update

### ISSUE THREAD

**Issue by verdverm** [peterbourgon/goop#1]
I had some difficulties getting back into my sound project because portaudio is updating and thus portaudio-go is updating.  Not sure it affects your code...

I see you have had some activity off the master branch?
What have you been working on?

I'm going to be hacking and using your code this weekend for a Startup Weekend.
Wish me luck!

Do you know of an easier way to message?

**Comment by peterbourgon** [comment]
Ah! Very sorry I missed this. Gotta update my notification settings. Hope the hack day went well.

This is my Forever Project so I'm always noodling with it, but I've taken a bit of a break (as you can see) as I learn a bit more on the theory. I'll probably pick it up again towards the spring/summer, and make a bunch of maintenance fixes like the Portaudio thing.
